# Generated by Django 5.1.2 on 2024-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task', models.CharField(max_length=255)),
                ('target_variable', models.CharField(max_length=255)),
                ('list_of_features', models.TextField(blank=True)),
                ('status', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('evaluation_metric', models.CharField(max_length=255)),
                ('evaluation_metric_value', models.FloatField()),
            ],
        ),
    ]
