# Generated by Django 5.1.2 on 2025-06-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automlapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("model_task_type", models.CharField(max_length=50)),
                (
                    "template_config",
                    models.JSONField(default=dict, help_text="Template configuration"),
                ),
                (
                    "chart_types",
                    models.JSONField(
                        default=list, help_text="List of chart types to generate"
                    ),
                ),
                (
                    "insight_types",
                    models.JSONField(
                        default=list, help_text="List of insight types to generate"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["model_task_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_insights",
                    models.TextField(
                        blank=True, help_text="AI-generated insights from Gemini"
                    ),
                ),
                ("report_type", models.CharField(default="analysis", max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "model_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="automlapp.modelentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataInsight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("feature_importance", "Feature Importance"),
                            ("data_distribution", "Data Distribution"),
                            ("correlation_analysis", "Correlation Analysis"),
                            ("missing_values", "Missing Values Analysis"),
                            ("outlier_detection", "Outlier Detection"),
                            ("class_balance", "Class Balance"),
                            ("performance_metrics", "Performance Metrics"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "insight_data",
                    models.JSONField(default=dict, help_text="Structured insight data"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Priority level (1=high, 5=low)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="aiapp.report",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChartData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("pie", "Pie Chart"),
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("scatter", "Scatter Plot"),
                            ("histogram", "Histogram"),
                            ("box", "Box Plot"),
                            ("correlation", "Correlation Matrix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "chart_config",
                    models.JSONField(
                        default=dict,
                        help_text="Chart configuration (colors, layout, etc.)",
                    ),
                ),
                (
                    "chart_data",
                    models.JSONField(
                        default=dict, help_text="Chart data (labels, values, etc.)"
                    ),
                ),
                (
                    "chart_image_base64",
                    models.TextField(
                        blank=True, help_text="Base64 encoded chart image"
                    ),
                ),
                (
                    "chart_html",
                    models.TextField(blank=True, help_text="Interactive HTML chart"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="aiapp.report",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
