# Generated by Django 5.1.2 on 2025-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="current_step",
            field=models.CharField(
                blank=True, help_text="Current processing step", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="progress_percentage",
            field=models.IntegerField(
                default=0, help_text="Progress percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="task_id",
            field=models.CharField(
                blank=True, help_text="Celery task ID", max_length=255, null=True
            ),
        ),
    ]
