# Generated by Django 5.1.2 on 2025-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0002_report_current_step_report_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='chart_code',
            field=models.TextField(blank=True, help_text='LLM-generated Python code for the chart'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='llm_reasoning',
            field=models.TextField(blank=True, help_text="LLM's reasoning for choosing and generating this chart"),
        ),
    ]
