# Generated by Django 5.1.2 on 2025-06-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0004_dashboardrun'),
        ('automlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('model_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dashboard', serialize=False, to='automlapp.modelentry')),
                ('charts', models.JSONField(default=list, help_text='Chart suggestions for this model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardRun',
        ),
    ]
