# Generated by Django 5.1.2 on 2025-06-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0005_dashboard_delete_dashboardrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
