# Generated by Django 5.1.2 on 2025-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0006_dashboard_description_dashboard_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status',
            field=models.CharField(default='pending', help_text='Dashboard generation status: pending, generating, completed, failed', max_length=20),
        ),
    ]
