# Generated by Django 5.1.2 on 2025-06-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0007_alter_dashboard_options_dashboard_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_content', models.TextField(help_text='Generated HTML profile content')),
                ('dataset_shape', models.CharField(help_text='Dataset shape (rows, columns)', max_length=50)),
                ('columns', models.TextField(help_text='JSON string of column names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_profiles', to='automlapp.modelentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model_entry',)},
            },
        ),
    ]
