# Generated by Django 5.1.2 on 2025-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelentry',
            name='date_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelentry',
            name='datetime_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
