# Generated by Django 5.1.2 on 2025-02-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('models', models.ManyToManyField(to='automlapp.modelentry')),
            ],
        ),
    ]
