name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push web image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-web:${{ github.sha }}

    - name: Build and push celery image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.celery
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-celery:${{ github.sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        containerAppName: automl-backend-web
        imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-web:${{ github.sha }}
        environmentVariables: |
          ENV=production
          DATABASE_URL=secretref:database-url
          REDIS_URL=secretref:redis-url
          LLM_API_KEY=secretref:llm-api-key
          LLM_BASE_URL=secretref:llm-base-url
          LLM_MODEL=secretref:llm-model

    - name: Deploy Celery to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        containerAppName: automl-backend-celery
        imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-celery:${{ github.sha }}
        environmentVariables: |
          ENV=production
          DATABASE_URL=secretref:database-url
          REDIS_URL=secretref:redis-url
          LLM_API_KEY=secretref:llm-api-key
          LLM_BASE_URL=secretref:llm-base-url
          LLM_MODEL=secretref:llm-model

    - name: Configure Celery Autoscaling
      uses: azure/cli@v1
      with:
        inlineScript: |
          az containerapp update \
            --name automl-backend-celery \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --min-replicas 0 \
            --max-replicas 5 \
            --scale-rule-name redis-queue-scaler \
            --scale-rule-type redis \
            --scale-rule-metadata "connectionStringSettingRef"="redis-url" "listName"="celery" "listLength"="5"
