name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push web image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-web:${{ github.sha }}

    - name: Build and push celery image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.celery
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-celery:${{ github.sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        container-app-name: automl-backend-web
        image-to-deploy: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-web:${{ github.sha }}
        environment-variables:
          - name: ENV
            value: production
          - name: DATABASE_URL
            secretRef: database-url
          - name: REDIS_URL
            secretRef: redis-url

    - name: Deploy Celery to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        container-app-name: automl-backend-celery
        image-to-deploy: ${{ secrets.ACR_NAME }}.azurecr.io/automl-backend-celery:${{ github.sha }}
        environment-variables:
          - name: ENV
            value: production
          - name: DATABASE_URL
            secretRef: database-url
          - name: REDIS_URL
            secretRef: redis-url

    - name: Configure Celery Autoscaling
      uses: azure/cli@v1
      with:
        inlineScript: |
          az containerapp update \
            --name automl-backend-celery \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --min-replicas 0 \
            --max-replicas 5 \
            --scale-rule-name redis-queue-scaler \
            --scale-rule-type redis \
            --scale-rule-metadata "connectionStringSettingRef"="redis-url" "listName"="celery" "listLength"="5"
